### ISSUE TITLE
为什么生成的文件大小是0呢？是我的参数有问题吗?麻烦帮我看下哈，谢谢。

### ISSUE THREAD

**Issue by wangzc66** [jameslz/fastx-utils#2]
我的barcode文件是如下：
13      ACT     G
14      CGAG    TTG
15      GTGAT   CGAG
16      TACTGG  ACTCTGG
代码如下：
seqtk_demultiplex -b 40.txt -1 rawdata/KZZ-CTWW-40_S40_L001_R1_001.fastq.gz -2 rawdata/KZZ-CTWW-40_S40_L001_R2_001.fastq.gz -l 1 -d ./

**Comment by jameslz** [comment]
有小的测试数据吗？

**Comment by wangzc66** [comment]
有的，怎么给您呢？ @jameslz

**Comment by jameslz** [comment]
选择你方便的共享方式，比如网盘，地址发到 jameslz@foxmail.com 就可以了。

**Comment by wangzc66** [comment]
好的，谢谢。

**Comment by wangzc66** [comment]
链接：https://pan.baidu.com/s/1jI7t2b8 密码：d6uf
这是我的测试数据的链接，里面包含了barcode文件，麻烦帮我测试下哈，谢谢

**Comment by wangzc66** [comment]
我的13号样本没有反向barcode，所以我把反向引物的第一个碱基，也就是G加到反向barcode上了 @jameslz ，这些信息在  实验信息.xlsx 有体现。

**Comment by jameslz** [comment]
我测试了，没有问题，执行之前，如果是Windows编辑的文件，最好使用dos2unix 格式化下。
![image](https://user-images.githubusercontent.com/1219504/34375662-a07760fe-eb22-11e7-8ca9-146b49be57e4.png)

**Comment by wangzc66** [comment]
谢谢您，这个问题解决了。

**Comment by liucong2016** [comment]
请教一下seqtk_demultiplex该如何安装？ 按照网上查到的装不了.........请求指导万分感谢

**Comment by jameslz** [comment]
使用biostack-suits 里的 atlas-utils demultiplex

**Comment by Sh1ne111** [comment]
Hi，
Great tool, can you share the source code for learning purposes?

chens

**Comment by jameslz** [comment]
atlas-utils(https://github.com/jameslz/atlas-utils)  and fastx-utils(https://github.com/kits-hub/fastx-utils) had been open sourced.
